// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _2024_b1_individueel.Data;

#nullable disable

namespace _2024_b1_individueel.Migrations
{
    [DbContext(typeof(GuessTheFlagDatabaseContext))]
    [Migration("20241009113514_AddFlagDecksToDb")]
    partial class AddFlagDecksToDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("_2024_b1_individueel.Models.Flag", b =>
                {
                    b.Property<Guid>("Identifier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CorrectAnswers")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("FlagDeckIdentifier")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Identifier");

                    b.HasIndex("FlagDeckIdentifier");

                    b.ToTable("FlagSet");
                });

            modelBuilder.Entity("_2024_b1_individueel.Models.FlagDeck", b =>
                {
                    b.Property<Guid>("Identifier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Identifier");

                    b.ToTable("FlagDeckSet");
                });

            modelBuilder.Entity("_2024_b1_individueel.Models.Flag", b =>
                {
                    b.HasOne("_2024_b1_individueel.Models.FlagDeck", null)
                        .WithMany("Flags")
                        .HasForeignKey("FlagDeckIdentifier");
                });

            modelBuilder.Entity("_2024_b1_individueel.Models.FlagDeck", b =>
                {
                    b.Navigation("Flags");
                });
#pragma warning restore 612, 618
        }
    }
}
