@startuml class

abstract class Entity {
  + Guid Identifier
}

class Flag {
  + string CountryCode
  + string CorrectAnswer

  + bool IsCorrectAnswer()
}

class FlagDeck {
  + List<Flag> Flags

  + FlagDeck Shuffle()
}

class Score {
  + string AchievedBy
  + int AchievedScore
  + FlagDeck FlagDeck
}


Entity <|-- Flag
Entity <|-- FlagDeck
Entity <|-- Score

FlagDeck --> Flag : 1:n
FlagDeck --> Score : 1:n

@enduml
