@startuml uc1_sequence

box Doorloop quiz #White

actor ":Leerling" as l
participant ":Quiz" as q
participant ":FlagDeck" as d
participant ":Flag" as f

activate l


l -> q : StartQuiz()
activate q
q -> d : ShuffleFlags()
activate d
q <-- d
deactivate d


loop FlagDeck.Flags > 0

q -> d : GetFlag()
activate d
q <-- d
deactivate d
l <-- q


l -> q : AnswerFlag()
q -> d : CheckAnswerCurrentFlag()
activate d
d -> f : CheckAnswer()
activate f
d <-- f
deactivate f
q <-- d
deactivate d
l <-- q

end


l <-- q


deactivate q
deactivate l
@enduml
